# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authentication.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61uthentication.proto\x12\x0c\x61uth_service\x1a\x1bgoogle/protobuf/empty.proto\"0\n\x0fGenericResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x03\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"T\n\rLoginResponse\x12\r\n\x05token\x18\x01 \x01(\t\x12\x34\n\rresponse_info\x18\x02 \x01(\x0b\x32\x1d.auth_service.GenericResponse\"3\n\rSignUpRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"U\n\x0eSignUpResponse\x12\r\n\x05token\x18\x01 \x01(\t\x12\x34\n\rresponse_info\x18\x02 \x01(\x0b\x32\x1d.auth_service.GenericResponse\"F\n\x0eLogoutResponse\x12\x34\n\rresponse_info\x18\x01 \x01(\x0b\x32\x1d.auth_service.GenericResponse2\xde\x01\n\x15\x41uthenticationService\x12@\n\x05Login\x12\x1a.auth_service.LoginRequest\x1a\x1b.auth_service.LoginResponse\x12\x43\n\x06SignUp\x12\x1b.auth_service.SignUpRequest\x1a\x1c.auth_service.SignUpResponse\x12>\n\x06Logout\x12\x16.google.protobuf.Empty\x1a\x1c.auth_service.LogoutResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'authentication_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GENERICRESPONSE']._serialized_start=67
  _globals['_GENERICRESPONSE']._serialized_end=115
  _globals['_LOGINREQUEST']._serialized_start=117
  _globals['_LOGINREQUEST']._serialized_end=167
  _globals['_LOGINRESPONSE']._serialized_start=169
  _globals['_LOGINRESPONSE']._serialized_end=253
  _globals['_SIGNUPREQUEST']._serialized_start=255
  _globals['_SIGNUPREQUEST']._serialized_end=306
  _globals['_SIGNUPRESPONSE']._serialized_start=308
  _globals['_SIGNUPRESPONSE']._serialized_end=393
  _globals['_LOGOUTRESPONSE']._serialized_start=395
  _globals['_LOGOUTRESPONSE']._serialized_end=465
  _globals['_AUTHENTICATIONSERVICE']._serialized_start=468
  _globals['_AUTHENTICATIONSERVICE']._serialized_end=690
# @@protoc_insertion_point(module_scope)
